name: cek
version: 0.1.0.0
github: "dannypsnl/cek"
license: BSD3
author: "Lîm Tsú-thuàn"
maintainer: "dannypsnl@gmail.com"
copyright: "2021 Lîm Tsú-thuàn"

extra-source-files:
  - README.md
  - ChangeLog.md

description: Please see the README on GitHub at <https://github.com/dannypsnl/virtual-machine/blob/develop/cek/README.md>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  cek-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cek
      - hspec
